### ISSUE TITLE
Varied training (feature request)

### ISSUE THREAD

**Issue by isti03** [adrcotfas/burpee-buddy#2]
I would really like to see a feature that allows you to repeat sequences of exercises. 
For example:
- 10 push-ups
- 20 squats
- 10 burpees
- repeat this sequence 3 times

**Comment by adrcotfas** [comment]
I was thinking of putting this app on ice since it was just an experiment with the proximity sensor.  
Unfortunately, the proximity can act completely different on different Android phones and I don't plan to implement a fix for every device with issues.  
At the moment I'm working on a different app, an interval timer which puts focus on the type of timer and not the exercises.

Are you using the auto-count feature?

**Comment by isti03** [comment]
@adrcotfas I think you got me wrong. I have no problem with the proximity sensor whatsoever. In fact, I really like this idea. It is just a feature request. Please read the description again. The exercises there are just examples. This feature request might overlap with the interval timer, which you are working on.

**Comment by adrcotfas** [comment]
I was just trying to say that I will not work on this app anymore and was curious if the auto-count feature is useful for you. The rest of my comment is off-topic.

**Comment by isti03** [comment]
OK, now I get it. But I definitely like the auto count feature. If you get back to it in the future, I would recommend implementing auto-count using the accelerometer and gyroscope as well.
